name: Build and Obfuscate BPB Panel

on: 
  push: 
    branches: 
      - main 
  schedule: 
    # Run every day at 1:00 am 
    - cron: "0 1 * * *"

permissions: 
  contents: write

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Set up the Node.js environment 
        uses: actions/setup-node@v4 
        with: 
          node-version: "latest"

      - name: Install dependencies 
        run: | 
          npm install -g javascript-obfuscator

      - name: Download BPB worker.js 
        run: | 
          wget -O origin.js https://raw.githubusercontent.com/bia-pain-bache/BPB-Worker-Panel/main/build/unobfuscated-worker.js

      - name: obfuscated BPB worker.js 
        run: | 
          javascript-obfuscator origin.js --output _worker.js \ 
            --compact true \ 
            --control-flow-flattening false \ 
            --dead-code-injection false \ 
            --identifier-names-generator mangled \ 
            --rename-globals false \ 
            --string-array true \ 
            --string-array-encoding 'rc4' \ 
            --string-array-threshold 0.75 \ 
            --transform-object-keys true \ 
            --unicode-escape-sequence true

      - name: Commit changes 
        uses: stefanzweifel/git-auto-commit-action@v5 
        with: 
          branch: main 
          commit_message: ':arrow_up: Update to latest BPB board' 
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>' 
          push_options: '--set-upstream'
